const dogBreeds = [
  "Affenpinscher",
  "Afgano",
  "Akita Japonés",
  "Basenji",
  "Basset Azul de Gascuña",
  "Basset Hound",
  "Basset Leonado de Bretaña",
  "Beagle",
  "Beauceron",
  "Bedlington Terrier",
  "Bergamasco",
  "Bichón Boloñés",
  "Bichón Frisé",
  "Bloodhound",
  "Bobtail",
  "Antiguo Pastor Inglés",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bóxer",
  "Boyero De Berna",
  "Boyero de Flandes",
  "Bracco Italiano",
  "Braco Alemán De Pelo Corto",
  "Braco Alemán De Pelo Duro",
  "Braco De Weimar",
  "Braco Húngaro",
  "Braco Húngaro De Pelo Duro",
  "Bretón", 
  "Buhund Noruego",
  "Bull Terrier",
  "Bull Terrier Miniatura",
  "Bulldog",
  "Bulldog Francés",
  "Bullmastiff",
  "Cairn Terrier",
  "Caniche Enano",
  "Caniche Grande",
  "Caniche Toy",
  "Carlino",
  "Cavalier King Charles Spaniel",
  "Cazador de Alces Noruego",
  "Chihuahua pelo largo",
  "Chihuahua pelo suave",
  "Chin Japonés",
  "Chow Chow pelo duro",
  "Chow Chow pelo suave",
  "Clumber Spaniel"
]

export default dogBreeds;